version: '3'

services:
  backend:
    image: euberdeveloper/democraffic-backend:latest
    restart: always
    env_file:
      - ./config/api.env
    volumes:
      - backend-stored:/server/stored
    ports:
      - "3000:3000"

  watchtower:
    image: containrrr/watchtower
    env_file:
      - ./config/watchtower.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json

volumes:
  backend-stored: